---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
  requests:
  storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
    template:
      metadata:
        labels:
          app: mysql
      spec:
        containers:
        - image: mysql:latest
          args:
          - "--ignore-db-dir=lost+found"
          imagePullPolicy: Always
          name: mysql
          ports:
          - containerPort: 3306 
            name: mysql
          env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: my-secret
                    key: ROOT_PASSWORD  
              - name: MYSQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: my-secret
                    key: MYSQL_DATABASE

          volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql/
        volumes:
        - name: mysql-data
          persistentVolumeClaim:
            clainName: mysql-data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec: 
  replicas: 3  
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: hmatheus00/backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80